### ISSUE TITLE
Bug: Structural directive + no input + as syntax

### ISSUE THREAD

**Issue by ntziolis** [ikatyang/angular-estree-parser#198]
We have created:
- a structural directive with no input
- and are using the `as`syntax to capture the `$implicit` value of the template context

The syntax check in html template (vscode) works as expected (no errors):
```html
<button
  *IsEmployee="as isEmployee"
  [disabled]="element.status === 1 || (!isDplEmployee && element.status === 2"
>
```

But when formatting the html (with prettier) the string `NgEstreeParser` is pretended to the `as` statement. Resulting in incorrect syntax:
```html
<button
  *IsEmployee="NgEstreeParser as isEmployee"
  [disabled]="element.status === 1 || (!isDplEmployee && element.status === 2"
>
```

Expected result:
- for the formatter to leave the as statement as is

This seems to be linked to the use of a fake [prefix](https://github.com/ikatyang/angular-estree-parser/blob/4c8cab3cdb62fb914fa61af187ea632d0766d377/src/utils.ts#L7).

Not sure if this is the right place to report this, I'd appreciate any pointers where you think this belongs.

**Comment by ikatyang** [comment]
Not quite sure why did you get that result as I'm not able to reproduce it on the Prettier playground, but I did find a bug that implicit variable bindings are not handled correctly. If you're able to reproduce it with Prettier, please open an issue on the Prettier repo with steps to reproduce.
